### ISSUE TITLE
When using multiple directories, you get some erroneous output about Added and Removed mods

### ISSUE THREAD

**Issue by utoc** [Watchful1/ModDetectorApi#1]
I have a feeling this is holdover from the tool you use in identifying mdpack submissions, here is a sample output:

```
PS mods> java -jar ModDetectorApi.jar ./1.7.10 ./
Removed: null
Removed: Advanced Generators
Removed: Advanced Genetics Mod
Removed: AE2 Stuff
Removed: AgriCraft
<snip>
```

And now putting the directories in another order:

```
PS mods> java -jar ModDetectorApi.jar ./ ./1.7.10
Added: null : ModDetectorApi.jar
Added: Advanced Generators : 0.9.16.99
Added: Advanced Genetics Mod : 1.5.9
Added: AE2 Stuff : 0.4.3.47
Added: AgriCraft : 1.7.10-1.3.1
<snip>
```

java version 1.8.0_45 on Windows 7.  This only seems to happen when using multiple directories in your arguments.  If I have neglected any important information, please let me know.  Thanks again for this tool.

**Comment by utoc** [comment]
Nevermind.  I just realized the second directory was intended to make a changelog, not to have multiple directories polled for jar files.  Sorry!

**Comment by Watchful1** [comment]
That's kinda funny. It's picking up itself.

But yeah, it parses recursively, so it should handle the 1.7.10 folder fine.
