### ISSUE TITLE
Another instance of "Couldn't download mods/json"

### ISSUE THREAD

**Issue by utoc** [Watchful1/ModDetectorApi#10]
Hi!

I tried running ModDectectorAPI this morning and came upon another instance of https://github.com/Watchful1/ModDetectorApi/issues/9

I did (im)patiently wait ten minutes to see if it was a minor hiccup in server availability but it seems to be ongoing since at least this morning although I can confirm its been working for the past month flawlessly.

Error here: http://i.imgur.com/ydpaKvw.png

Screenshot of HTTP error here: http://i.imgur.com/EJFrOTL.png

**Comment by Watchful1** [comment]
Thanks for the report, the site is now back up.

I should add a client side caching feature, but I never was a big fan of this code, so I don't know if I'll ever get myself to work on it again.
