### ISSUE TITLE
Website is down again

### ISSUE THREAD

**Issue by utoc** [Watchful1/ModDetectorApi#11]
I hate to keep bugging you.. the json site is down again.

`
Couldn't read http://www.feed-the-beast.com/mods/json
Could not download json, aborting
`

Totally open to another tool that doesnt cause you extra work if you have a suggestion; I haven't found a better tool to diff between versions for a changelog.

**Comment by Watchful1** [comment]
I'll look into it.

The fundamental problem with this tool is that it depends on the info set in the mod by the author. That's correct 95% of the time, but a decent amount of the time it isn't. Especially version numbers, when the author updates the mod but forgets to change the version in the mcmod.info.

I wanted to expand the functionality to check a bunch of sources, curse, our site, not enough mods, etc, and try some kind of machine learning to determine the correlation between all the sources and the actual mod files. But I never really thought that many people would use it, and it would be a lot of work, so I kinda gave up.

**Comment by Watchful1** [comment]
Back up now.
