### ISSUE TITLE
Can't get it to work.

### ISSUE THREAD

**Issue by SFort** [Watchful1/ModDetectorApi#12]
Command: 
java -jar ModDetectorApi.jar -v test

Return:
Loading 1879 mods from api
Skipping, no id's : advcancedmachinesatomicstryker

The "test" folder was empty.
(Sorry if this is user error)

**Comment by Watchful1** [comment]
I'm not sure what you're trying to do. Why are you running it on an empty folder?

**Comment by SFort** [comment]
User error,
I taught it should be executed in the mods folder and needed a specified location to return the log to.
Thanks for clearing it up(Great mod dev tool)
