### ISSUE TITLE
Issue with JSON from www/legacy

### ISSUE THREAD

**Issue by utoc** [Watchful1/ModDetectorApi#9]
Sorry to bug you.

I've tried twice now since the legacy server came back online to run the ModDetectorApi to no avail.  I even cloned the project and changed statics.java to use the legacy.feed-the-beast URL rather than www.feed-the-beast but still get a failure to download the json.

```
Couldn't read http://legacy.feed-the-beast.com/mods/json
Could not download json, aborting
```

I even tried it on my unix server to make sure it wasn't my computer, same issue:

```
[minecraft@cubby] /home/minecraft/work > java -jar ModDetectorApi.jar ~/bbqsauce/mods
Couldn't read http://legacy.feed-the-beast.com/mods/json
Could not download json, aborting

[minecraft@cubby] /home/minecraft/work > java -jar ModDetectorApi.derp.jar ~/bbqsauce/mods
Couldn't read http://www.feed-the-beast.com/mods/json
Could not download json, aborting
```

Thoughts?

**Comment by Watchful1** [comment]
I believe this is due to a cloudflare change and the useragent not being set properly. I'll take a look when I'm at my main computer.

**Comment by Watchful1** [comment]
Fixed, new release.

https://github.com/Watchful1/ModDetectorApi/releases/tag/1.1.2
